{
 "title": "FastAPI Metrics",
 "description": "FastAPI Application Metrics Dashboard",
 "tags": [
  "fastapi",
  "monitoring"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "handler",
    "query": {
     "query": "label_values(http_request_duration_seconds_count, handler)"
    }
   },
   {
    "name": "method",
    "query": {
     "query": "label_values(http_request_duration_seconds_count, method)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count{handler=\"/items\", method=\"GET\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Per Second (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count{handler=\"/items\", method=\"GET\"}[1m])",
     "legendFormat": "{{handler}} - RPS"
    }
   ]
  },
  {
   "title": "Latency (95th percentile)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{handler=\"/items\", method=\"GET\"}[1m])) by (le)) * 1000",
     "legendFormat": "95th Percentile"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "Memory Usage" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "CPU Usage"
    }
   ]
  }
 ]
}